### ISSUE TITLE
soplex install error

### ISSUE THREAD

**Issue by maozhitao** [SBRG/soplex_cython#5]
![image](https://user-images.githubusercontent.com/3759962/32424316-8d4b8104-c2e6-11e7-9ebf-9af661ea93cc.png)

redhat system,SoPlex 3.0.0.

cd /home/mzt/mysoft/soplex/src
patch -b < /home/mzt/mysoft/soplex_cython/long-double.patch
cd ..
export USRCPPFLAGS="-DWITH_LONG_DOUBLE"
make SHARED=true GMP=true ZLIB=false VERBOSE=true
ar crs libsoplex.a obj/*/lib/*
cp /home/mzt/mysoft/soplex/libsoplex.a /home/mzt/mysoft/soplex_cython
cd /home/mzt/mysoft/soplex_cython
bash build.sh

Which step was wrong?

**Comment by coltonlloyd** [comment]
Which version of Cython are you using?

**Comment by coltonlloyd** [comment]
I pushed a simplified install to the `devel_windows` branch. It installs Soplex 3.0.1, so you don't need to the apply the patch.

Let me know if that works for you!

**Comment by maozhitao** [comment]
Thank you very much for your answer, the problem has been solved. This is due to two versions of python on the machine that can be installed properly with root privileges.

**Comment by coltonlloyd** [comment]
Good to hear. Let me know if you have any other issues.
